Make sure connection preface is always sent first
kazu-yamamoto/http2 pull request #33
Opened 2021-11-29 10:33 UTC by pcapriotti

This fixes a race condition in the client between the `frameSender` thread and the main thread, in the case where a SETTINGS frame is sent in response to a server SETTINGS frame before the connection preface has had a chance to be sent.

This PR also includes a commit to prevent client threads from waiting forever on stream input when the client `frameSender` thread dies. This is useful in its own right, I think, but in particular it is needed to make the test for the above fix work.

2021-11-29 23:28 UTC, kazu-yamamoto requested changes
Would you fix the race issue only in this PR?
Based on the experience of `quic`, I think that the waiting-forever issue should be fixed by the thread tree feature provided by `async`.

2021-12-03 08:53 UTC, pcapriotti commented
> Would you fix the race issue only in this PR? Based on the experience of `quic`, I think that the waiting-forever issue should be fixed by the thread tree feature provided by `async`.

I could do that, but then I'm not sure how to set up a test for it. Could you elaborate on how you want the waiting-forever issue to be fixed? I can try writing a patch for that first.

2021-12-10 10:42 UTC, pcapriotti commented
I rebased this branch so that it only contains the preface race fix. I wrote a patch employing async to propagate exceptions and thread termination to the main client thread, based on this one: https://github.com/wireapp/http2/commit/617c685b1c7727b77a006c4f5d4d65f3cc52fded, and the preface test is now based on both of these patches: https://github.com/wireapp/http2/commit/fb4afa7aa16641f7642b797d55af3465e6a103fa.

Should I submit these as separate PRs or include them here?

2021-12-10 13:51 UTC, pcapriotti commented
> If you kindly make this PR in this order, I'd love to merge.

Done.

2021-12-10 22:36 UTC, merged

2021-12-10 22:36 UTC, kazu-yamamoto commented
Merged. Thank you for your contribution!
If you wish, I will release a new version.

2021-12-11 06:37 UTC, pcapriotti commented
Thanks for merging!

>  If you wish, I will release a new version.

We are fine depending on a git version, so up to you. Also, I will probably have more PRs coming in the next few days.

2021-12-12 22:40 UTC, kazu-yamamoto commented
So, I wait for the PRs.